# Generated by Django 6.0.3 on 2026-04-17 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_faqsuggestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faqsuggestion',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
