# Generated by Django 6.0.3 on 2026-04-17 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0002_announcement_archived_at_announcement_archived_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='target_users',
            field=models.JSONField(blank=True, default=list, help_text='List of user IDs/names when scope=specific_users. Format: ["user1", "user2"]'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='scope',
            field=models.CharField(choices=[('campus_wide', 'Entire Campus (all users)'), ('all_college', 'All College Students'), ('basic_ed_only', 'Basic Education Only'), ('department', 'Specific Department Only'), ('specific_users', 'Specific Users (by name)')], default='campus_wide', max_length=20),
        ),
    ]
