# Generated by Django 6.0.4 on 2026-04-10 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='is_anonymous',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='feedback',
            name='location',
            field=models.CharField(blank=True, help_text='Optional campus location name this feedback relates to', max_length=200, null=True),
        ),
    ]
